language:
  python

python:
  - 3.6

services:
    - elasticsearch

install:
  - make install

before_script:
  - sleep 30
  - curl localhost:9200

script:
  - make test

after_success:
  - coveralls
